export const NAV = [
  { section: "FUNNEL", items: [
    { href: "/", id: "command", label: "Command" },
    { href: "/leads", id: "leads", label: "Leads" },
    { href: "/prospects", id: "prospects", label: "Prospects" },
    { href: "/dialer", id: "dialer", label: "Dialer" },
    { href: "/inbox", id: "inbox", label: "Inbox" },
    { href: "/ads", id: "ads", label: "Ads" },
    { href: "/partners", id: "partners", label: "Partners" },
  ]},
  { section: "CLIENTS", items: [
    { href: "/customers", id: "customers", label: "Customers" },
    { href: "/billing", id: "billing", label: "Billing" },
  ]},
  { section: "BUILD", items: [
    { href: "/work", id: "work", label: "The floor" },
    { href: "/sessions", id: "sessions", label: "Sessions" },
    { href: "/playbooks", id: "playbooks", label: "Playbooks" },
  ]},
  { section: "SYSTEM", items: [
    { href: "/memory", id: "memory", label: "Memory" },
    { href: "/spending", id: "spending", label: "Spending" },
    { href: "/connect", id: "connect", label: "Connect Vercel" },
    { href: "/github", id: "github", label: "Our GitHub" },
    { href: "/settings", id: "settings", label: "Settings" },
  ]},
] as const;

export const TITLES: Record<string, string> = {
  "/": "Command — dominate the market",
  "/pipeline": "Leads",
  "/leads": "Leads",
  "/prospects": "Prospects — firms we want",
  "/dialer": "Twilio power dialer",
  "/sms": "Inbox — every thread",
  "/ads": "Zernio ads",
  "/partners": "Partner dossier",
  "/work": "The floor — everything the AI is doing",
  "/sessions": "Sessions — every Claude Code on the floor",
  "/manager": "Sessions — every Claude Code on the floor",
  "/inbox": "Inbox — every thread",
  "/approvals": "The floor — everything the AI is doing",
  "/changes": "The floor — everything the AI is doing",
  "/org": "The AI team",
  "/playbooks": "Playbooks",
  "/customers": "Customer dossier",
  "/sales": "Leads",
  "/billing": "Billing & margin",
  "/marketing": "Ads",
  "/team": "Sessions — every Claude Code on the floor",
  "/memory": "Memory",
  "/spending": "Spending",
  "/connect": "Connect Vercel",
  "/github": "Our GitHub",
  "/settings": "Settings",
};
