export const NAV = [
  { section: "FUNNEL", items: [
    { href: "/", id: "command", label: "Command" },
    { href: "/pipeline", id: "pipeline", label: "Pipeline" },
    { href: "/leads", id: "leads", label: "Leads" },
    { href: "/prospects", id: "prospects", label: "Prospects" },
    { href: "/dialer", id: "dialer", label: "Dialer" },
    { href: "/sms", id: "sms", label: "SMS" },
    { href: "/ads", id: "ads", label: "Ads" },
    { href: "/partners", id: "partners", label: "Partners" },
  ]},
  { section: "CLIENTS", items: [
    { href: "/customers", id: "customers", label: "Customers" },
    { href: "/inbox", id: "inbox", label: "Inbox" },
    { href: "/billing", id: "billing", label: "Billing" },
  ]},
  { section: "BUILD", items: [
    { href: "/work", id: "work", label: "Live work" },
    { href: "/manager", id: "manager", label: "Head Wrangler" },
    { href: "/approvals", id: "approvals", label: "Needs you" },
    { href: "/changes", id: "changes", label: "Changes" },
    { href: "/playbooks", id: "playbooks", label: "Playbooks" },
  ]},
  { section: "SYSTEM", items: [
    { href: "/team", id: "team", label: "Your team" },
    { href: "/memory", id: "memory", label: "Memory" },
    { href: "/spending", id: "spending", label: "Spending" },
    { href: "/connect", id: "connect", label: "Connect Vercel" },
    { href: "/github", id: "github", label: "Our GitHub" },
    { href: "/settings", id: "settings", label: "Settings" },
  ]},
] as const;

export const TITLES: Record<string, string> = {
  "/": "Command — dominate the market",
  "/pipeline": "Pipeline",
  "/leads": "Lead dossier",
  "/prospects": "Prospects — firms we want",
  "/dialer": "Twilio power dialer",
  "/sms": "SMS — every book",
  "/ads": "Zernio ads",
  "/partners": "Partner dossier",
  "/work": "Live work",
  "/manager": "Head Wrangler",
  "/inbox": "Inbox",
  "/approvals": "Needs you",
  "/changes": "All changes",
  "/org": "The AI team",
  "/playbooks": "Playbooks",
  "/customers": "Customer dossier",
  "/sales": "Pipeline",
  "/billing": "Billing & margin",
  "/marketing": "Ads",
  "/team": "Your team",
  "/memory": "Memory",
  "/spending": "Spending",
  "/connect": "Connect Vercel",
  "/github": "Our GitHub",
  "/settings": "Settings",
};
